--- 
title: "Declaring and Diagnosing Research Designs"
author: "Graeme Blair, Jasper Cooper, Alexander Coppock, and Macartan Humphreys"
site: bookdown::bookdown_site
documentclass: book
bibliography: [bib/book.bib, bib/packages.bib]
biblio-style: apsr
link-citations: yes
description: "describe the book"
---

# Preface 

```{r bib-setup, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, cache = TRUE)
```

With this book, we hope to promote a new, comprehensive way of thinking about research designs in the social sciences. We hope this way of thinking will make research designs more transparent and more robust. But we also hope it will make research design easier, easier to produce good designs, but also easier to share designs and build off of the designs that others have developed.

The core idea is to start think of a design as an object that can be interrogated. The design encodes your beliefs about the world, it describes your questions, and it lays out  how you go about answering those questions, in terms both of what data you use and how you use it. A key idea is that all of these features can be provided in code and if done right the information provided is enough to be able to simulate a run of the design and assess its properties. 

For a researcher, being able to simulate a design puts you in a powerful position as you can then start assessing the conditions under which a design perfoms well or badly.

For a reader, a complete declaration lets you quickly examine the analytic core of a design. As you work through designs in this book we hope you will develop a nose for quickly parsing what goes in the model, what are the kinds of inquiries you should expect to see, what are the data strategies, what are analysis strategies, and how these all link together.

What this book will not do 

  - derive estimators
  - no analytic results
  - no optimality guarantees
  - GIGO

