# MIDA

Research designs are the procedures we use to learn about the world as we imagine it. Research designs vary according to how we imagine the world, the questions we want answer, the information we collect, and how we summarize the information in order to yield an answer. 





Interviews, surveys, case studies, randomized experiments, laboratory games, [etc], are all research designs



All empirical research designs gather and analyze information in order to answer a question about the world, stated in terms of a background model. 


These four features form the basis of the "MIDA" framework that we will rely on to describe designs. MIDA stands for "model," "inquiry," "data strategy," and "answer strategy." The first two components of a design are theoretical. The model of the world that is in researchers minds may correspond to the real world more or less well, but the model is certainly not the same thing as the real world. The inquiry is a question about the world, expressed in terms of the model. Because the inquiry can only be expressed in model terms, it is also theoretical. By contrast, the second two components of a research design - the data strategy and answer strategy - take place in the real world and are not theoretical. The data strategy describes how the research will obtain new information, so includes choices like case selection, sampling procedures, randomization protocols, questionaire design, participant observation techniques, and the like. The answer strategy is how you process the new information. The answer strategy is more than just the choice of estimator -- it's the full set of choices that map the data into the table and figures in the report. For quantitative designs, these choices include how "raw data" are processed into "clean data," which estimators will be applied, and which results will be presented. For qualitative designs, the answer strategy includes procedures for summarizing interviews, field notes, or original source documents. 

Formally, we defined a causal \textbf{model}, $M$, of how the world works, following Pearl's definition of a probabilistic causal model \citep{Pearl2009}. A casual model itself is made up of three components: 

1) The variables $X$ and their ranges. The variables in $X$ can themselves be partitioned into  endogenous ($V$) and exogenous ($U$) variables.

2) The functional relationships ($F$) between variables. The functional relationships describe how each variable in the model does or does not causally affect the others. Sometimes these functional relationships are described by potential outcomes functions.

3) A probability distribution over the exogenous variables, $P(U)$. 

Many features of a probabalistic causal model can be encoded in a Directed Acyclic Graph, or DAG. It shows the variables and the presence or absence of functional relationships between variables.  It does not encode the functional forms of those relationships or even the strength of the causal effect. It is difficult to represent heterogeneity on a DAG. The DAG does not show the $P(U)$. 


The inquiry generates the answer-under-the-model, or $a^M$. 






<!-- We make heavy use of a fairly general framework for describing the core elements of a research design. The basic idea is a research design is a specification of a problem and a strategy to answer it. We build on two influential frameworks. @kkv1994 enumerate four components of a research design: a theory, a research question, data, and an approach to using the data. @geddes2003paradigms articulates the links between theory formation, research question formulation, case selection and coding strategies, and strategies for case comparison and inference. In both cases the set of steps are closely aligned to those in the framework we propose. In the exposition, we also employ elements from @Pearl2009 approach to structural modeling, which provides a syntax for mapping design inputs to design outputs as well as the potential outcomes framework as presented, for example, in @Imbens2015, which many political scientists use to clarify their inferential targets. We characterize the design problem at a high level of generality with the central focus being on the relationship between questions and answer strategies.  -->


## Elements of a Research Design

The specification of a problem requires a description of the world and the question to be asked about the world as described. The answering requires a description of what information is used and how conclusions are reached given the information. 

At its most basic we think of a research design, $\Delta$, as including four elements $<M,I,D,A>$:

*  A \textbf{model}, $M$, of how the world works. In general following Pearl's definition of a probabilistic causal model we will assume that a model contains three core elements. First, a specification of the variables $X$  about which research is being conducted. This includes endogenous and exogenous variables ($V$ and $U$ respectively) and the ranges of these variables. In the formal literature this is sometimes called the \textit{signature} of a model [@halpern2000].   Second, a specification of how each endogenous variable depends on other variables (the ``functional relations'' or, as in @Imbens2015, ``potential outcomes''), $F$. Third, a probability distribution over exogenous variables, $P(U)$.  

* An \textbf{inquiry}, $I$, about the distribution of variables, $X$, perhaps given interventions on some variables.  Using Pearl's notation we can distinguish between questions that ask about the conditional values of variables, such as $\Pr(X_1 | X_2 =1)$ and questions that ask about values that would arise under interventions: $\Pr(X_1 | do(X_2 = 1))$.\footnote{
    The distinction lies in whether the conditional probability is recorded through passive observation or active intervention to manipulate the probabilities of the conditioning distribution. For example, $\Pr(X_1 | X_2 =1)$ might indicate the conditional probability that it is raining, given that Jack has his umbrella, whereas $\Pr(X_1 | do(X_2 =1))$ would indicate the probability with which it would rain, given Jack is made to carry an umbrella.
  } We let $a^M$ denote the answer to $I$ \textit{under the model}. Conditional on the model, $a^M$ is the value of the estimand, the quantity that the researcher wants to learn about.  

* A \textbf{data} strategy, $D$, generates data $d$ on $X$. Data $d$ arises, under model $M$ with probability $P_M(d|D)$. The data strategy includes sampling strategies and assignment strategies, which we denote with $P_S$ and $P_Z$ respectively. Measurement techniques are also a part of data strategies and can be thought of as a selection of observable variables that carry information about unobservable variables.

* An **answer** strategy, $A$, that generates answer $a^A$ using data $d$. 


A key feature of this bare specification is that if $M$, $D$, and $A$ are sufficiently well described, the answer to question $I$ has a distribution $P_M(a^A|D)$. Moreover, one can construct a distribution of comparisons of this answer to the correct answer, under $M$, for example by assessing $P_M(a^M-a^A|D)$. One can also compare this to results under different data or analysis strategies, $P_M(a^M-a^A|D')$ and $P_M(a^M-a^{A'}|D)$, and to answers generated under alternative models, $P_M(a^{M'}-a^{A}|D)$, as long as these possess signatures that are consistent with inquiries and answer strategies.  


*MIDA* captures the analysis-relevant features of a design, but it does not describe substantive elements, such as how theories are derived or interventions are implemented. Yet many other aspects of a design that are not explicitly labeled in these features enter into this framework if they are analytically relevant. For example, logistical details of data collection such as the duration of time between a treatment being administered and endline data collection enter into the model if the longer time until data collection affects subject recall of the treatment. However, information in {\it MIDA} is typically insufficient to assess those substantive elements, an important and separate part of assessing the quality of a research study.